In [1]:
import numpy as np

In [2]:
# create a 1-dimension array
arr1 = np.array([1, 2, 3])
print("Rank 1 array")
print(arr1)

# get the data type of the entire array
print(type(arr1))

# get the data type of the items in the array
print(arr1.dtype)

# get the shape of the array
print(arr1.shape)

# retrieve each item in the array using indexing
print(arr1[0], arr1[1], arr1[2])

# reassign value to the item in index 2 to 4
arr1[2] = 4
print(arr1)

Rank 1 array
[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1 2 3
[1 2 4]


In [3]:
# create a 2-dimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nRank 2 array")
print(arr2)

# get the data type of the entire array
print(type(arr2))

# get the data type of the items in the array
print(arr2.dtype)

# get the shape of the array
print(arr2.shape)

# retrieve 1st elem in the 1st list
print(arr2[0, 0])

# retrieve every elem in the 1st list
print(arr2[0, :])

# retrieve 1st elem in the 2nd list
print(arr2[1, 0])

# retrieve the second list
print(arr2[1, :])


Rank 2 array
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
1
[1 2 3]
4
[4 5 6]


In [4]:
# create a nested array using the ndmin key for minimum dimension
arr3 = np.array(np.arange(0, 6), ndmin=2)
print("\nRank 3 array")
print(arr3)

# get the data type of the entire array
print(type(arr3))

# get the data type of the items in the array
print(arr3.dtype)

# get the shape of the array
print(arr3.shape)

# retrieve 1st item in the nested array
print(arr3[0, 0])

# retrieve 3rd item in the nested array
print(arr3[0, 2])

# retrieve the inner array
print(arr3[-1])


Rank 3 array
[[0 1 2 3 4 5]]
<class 'numpy.ndarray'>
int64
(1, 6)
0
2
[0 1 2 3 4 5]


In [5]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2, 2))
print("zero array")
print(zero)

# create an array of ones with 1 dim and size of 2 each
one = np.ones((1, 2))
print("\nones array")
print(one)

# create a new array with given shape, type, and filled with 5 as the value
constant = np.full((2, 2), 5)
print("\nconstant array")
print(constant)

# create a 2-d array with 1 on the diagonal and 0 in other positions
diag = np.eye(3)
print("\ndiagonal ones array")
print(diag)

# diag starts at index 1
diag = np.eye(4, k=1)
print("\nshifted diagonal ones array")
print(diag)

# create an array with random values
rand = np.random.random((2, 2))
print("\nrandom array")
print(rand)

# generate an evenly spaced numbers between 0 and 1, excluding the endpoint
even_spaced = np.linspace(0, 1, num=10)
print("\nevenly spaced array")
print(even_spaced)

zero array
[[0. 0.]
 [0. 0.]]

ones array
[[1. 1.]]

constant array
[[5 5]
 [5 5]]

diagonal ones array
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

shifted diagonal ones array
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

random array
[[0.98477857 0.69996772]
 [0.15955322 0.43274687]]

evenly spaced array
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
# reshape into a 2x3 array (2 rows, 3 columns)
print("Original array:", arr3)
arr_reshaped = arr3.reshape(2, 3)
print("Reshaped array (2x3):\n", arr_reshaped)



Original array: [[0 1 2 3 4 5]]
Reshaped array (2x3):
 [[0 1 2]
 [3 4 5]]


In [7]:
# create a 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# resizing to a bigger array - this will repeat elements
arr_resized = np.resize(arr, (3, 3))
arr_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [8]:
# Flatten array
flattened = arr_resized.flatten()
print("Flattened array: ", flattened)

Flattened array:  [1 2 3 4 5 6 1 2 3]


In [9]:
# Create 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Use flat iterator to iterate over each element
for element in arr.flat:
    print(element)

1
2
3
4
5
6


In [11]:
transposed = arr.reshape(2, 3).T
print("Transposed array: \n", transposed)

Transposed array: 
 [[1 4]
 [2 5]
 [3 6]]


In [12]:
# create a 2x3 array

arr = np.array([[1, 2, 3], [4, 5, 6]])

# create another array to concatenate

arr2 = np.array([[12, 13, 14], [15, 16, 17], [18, 19, 20]])

# concatenate along rows (axis=0)

concatenated = np.concatenate((arr, arr2), axis=0)

print("Concatenated along rows:\n", concatenated)

# stack arrays vertically using vstack

vstacked = np.vstack((arr, arr2))

print("Vertically stacked:\n", vstacked)

Concatenated along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
Vertically stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [13]:
# create an array with repeated elements
dup_arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 6])

# find the unique elements
unique_elements = np.unique(dup_arr)
print("Unique elements:", unique_elements)

# find the unique elements and their counts
unique_elements, counts = np.unique(dup_arr, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts of each unique element:", counts)

# find the unique elements and the indices of the first occurrence
unique_elements, indices = np.unique(dup_arr, return_index=True)
print("Unique elements:", unique_elements)
print("Indices of first occurrence:", indices)

Unique elements: [1 2 3 4 5 6]
Unique elements: [1 2 3 4 5 6]
Counts of each unique element: [1 2 1 3 2 1]
Unique elements: [1 2 3 4 5 6]
Indices of first occurrence: [0 1 3 4 7 9]


In [14]:
# create a 1D array
arr = np.arange(12)
print("Original array:", arr)

# reshape to 3x4 array
reshaped_arr = np.reshape(arr, (3, 4))
print("Reshaped array (3x4):\n", reshaped_arr)

# basic indexing
# extract a single element
element = reshaped_arr[1, 2]  # element at row 1, column 2
print("Element at indices (1, 2):", element)

# slicing
# slice a subarray
subarray = reshaped_arr[:, 1:3]  # all rows, columns 1 and 2
print("Subarray (columns 1 and 2):\n", subarray)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at indices (1, 2): 6
Subarray (columns 1 and 2):
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [15]:
# fancy indexing
row_indices = [0, 1, 2]  # first, second, and third rows
col_indices = [2, 1, 0]  # third, second, and first columns

selected_elements = reshaped_arr[row_indices, col_indices]
print("Selected elements using fancy indexing:", selected_elements)

Selected elements using fancy indexing: [2 5 8]


In [17]:
# create a boolean mask
mask = reshaped_arr > 5  # filter elements greater than 5
print("\nBoolean mask:\n", mask)

# use the mask to select elements
filtered = reshaped_arr[mask]
print("Filtered elements (greater than 5):", filtered)


Boolean mask:
 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
Filtered elements (greater than 5): [ 6  7  8  9 10 11]


In [18]:
# element-wise addition
added = reshaped_arr + 10
print("Array after adding 10 to each element:\n", added)

# element-wise multiplication
multiplied = reshaped_arr * 2
print("Array after multiplying each element by 2:\n", multiplied)

Array after adding 10 to each element:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Array after multiplying each element by 2:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [19]:
# dot product
# create two 1D arrays (vectors)
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

# compute the dot product
dot_product = np.dot(vec1, vec2)
print("Dot product of vec1 and vec2:", dot_product)

Dot product of vec1 and vec2: 32


In [20]:
# create two 2D arrays (matrices)
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# compute the matrix product
matrix_product = np.matmul(mat1, mat2)
print("Matrix product using np.matmul():\n", matrix_product)

Matrix product using np.matmul():
 [[19 22]
 [43 50]]


In [21]:
import numpy as np

# matrices
mat1 = np.array([[1, 2],
                 [3, 4]])

mat2 = np.array([[5, 6],
                 [7, 8]])

# dot product
dot_result = np.dot(mat1, mat2)

# matrix multiplication
matmul_result = np.matmul(mat1, mat2)

print("Dot product result:\n", dot_result)
print("\nMatmul result:\n", matmul_result)

Dot product result:
 [[19 22]
 [43 50]]

Matmul result:
 [[19 22]
 [43 50]]


In [22]:
# NumPy has built-in support for broadcasting
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])

# add each value from a to each element of b
c = a + b
print("c:\n", c)

# this is the same broadcasting process using np.broadcast()
bc = np.broadcast(a, b)
x = np.zeros(bc.shape)

x.flat = [a_val + b_val for (a_val, b_val) in bc]
print("\nx:\n", x)

c:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]

x:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [23]:
# create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# calculate the mean (average)
mean_value = np.mean(arr)
print("Mean:", mean_value)

# calculate the median
median_value = np.median(arr)
print("Median:", median_value)

# calculate the standard deviation
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

# find the minimum value
min_value = np.min(arr)
print("Minimum value:", min_value)

# find the maximum value
max_value = np.max(arr)
print("Maximum value:", max_value)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10


In [24]:
# generate a 2x3 array of random numbers between 0 and 1
rand_array = np.random.rand(2, 3)
print("Random array using np.random.rand():\n", rand_array)

# generate a 3x3 array from standard normal distribution
randn_array = np.random.randn(3, 3)
print("\nRandom array using np.random.randn():\n", randn_array)

# generate a 4x4 array of random integers between 10 and 50
randint_array = np.random.randint(10, 50, size=(4, 4))
print("\nRandom array using np.random.randint():\n", randint_array)

Random array using np.random.rand():
 [[0.51297943 0.370202   0.92371721]
 [0.50216925 0.48402407 0.3607806 ]]

Random array using np.random.randn():
 [[-1.00406182  2.57752248 -1.37821188]
 [ 1.68295951 -0.29979057 -0.38951661]
 [ 0.49007624 -0.19609763 -0.19971324]]

Random array using np.random.randint():
 [[22 27 27 40]
 [29 40 17 38]
 [19 12 38 46]
 [46 49 11 19]]


In [25]:
# save the rand_array to a text file
np.savetxt('array_data.txt', rand_array, delimiter=',', fmt='%.2f')
print("Array has been saved to 'array_data.txt'")

# load the array from the text file
loaded_array = np.loadtxt('array_data.txt', delimiter=',')
print("Array loaded from 'array_data.txt':\n", loaded_array)

Array has been saved to 'array_data.txt'
Array loaded from 'array_data.txt':
 [[0.51 0.37 0.92]
 [0.5  0.48 0.36]]
