In [2]:
import numpy as np

In [3]:
dt = np.array(range(1, 10))
print(dt.dtype)
dt

int64


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
dt_1 = np.array(range(1, 10),dtype=np.float64)
print(dt_1.dtype)
dt_1

float64


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
import numpy as np

# create structured data type
dt = np.dtype([('name', 'U20'), ('age', np.int64), ('points', np.float64)])
print(dt)

# <U20 is a Unicode string with a maximum length of 20 characters
# <i8 is a 64-bit integer
# <f8 is a 64-bit float

# apply it to ndarray object called student
student = np.array([
    ('student_A', 20, 100),
    ('student_B_has_a_very_long_name', 20, 98),
    ('student_C', 21, 95)
], dtype=dt)

student

[('name', '<U20'), ('age', '<i8'), ('points', '<f8')]


array([('student_A', 20, 100.), ('student_B_has_a_very', 20,  98.),
       ('student_C', 21,  95.)],
      dtype=[('name', '<U20'), ('age', '<i8'), ('points', '<f8')])

In [8]:
student['age']

array([20, 20, 21])

In [10]:
student['name']


array(['student_A', 'student_B_has_a_very', 'student_C'], dtype='<U20')

In [11]:
student['points']

array([100.,  98.,  95.])