In [1]:
import numpy as np

In [2]:
# 1. Matrix Creation

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.eye(3)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# 2. Matrix Multiplication

C = np.matmul(A, B)

print("Matrix C = A x B:\n", C)

Matrix C = A x B:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
# 3. Element-wise Operations

C = C + 5
print("Matrix C after adding 5:\n", C)

C_sqrt = np.sqrt(C)
print("\nSquare root of each element in C:\n", C_sqrt)

Matrix C after adding 5:
 [[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]

Square root of each element in C:
 [[2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739]]


In [5]:
# 4. Row and Column Sums

row_sums = np.sum(C, axis=1)
column_sums = np.sum(C, axis=0)

print("Row sums:", row_sums)
print("Column sums:", column_sums)

Row sums: [21. 30. 39.]
Column sums: [27. 30. 33.]


In [6]:
# 5. Transpose and Flatten

C_transposed = C.T
C_flattened = C_transposed.flatten()

print("Transposed C:\n", C_transposed)
print("\nFlattened transposed C:\n", C_flattened)

Transposed C:
 [[ 6.  9. 12.]
 [ 7. 10. 13.]
 [ 8. 11. 14.]]

Flattened transposed C:
 [ 6.  9. 12.  7. 10. 13.  8. 11. 14.]


In [7]:
# 6. Linear Algebra Operations

det_A = np.linalg.det(A)
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Determinant of A:", det_A)
print("\nEigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)

Determinant of A: 6.66133814775094e-16

Eigenvalues of A:
 [ 1.61168440e+01 -1.11684397e+00 -3.21775239e-16]

Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [8]:
# 7. Normalized Matrix

def normalize_matrix(mat):
    min_value = np.min(mat)
    max_value = np.max(mat)
    normalized = (mat - min_value) / (max_value - min_value)
    return normalized

normalized_C = normalize_matrix(C)

print("Normalized C:\n", normalized_C)

Normalized C:
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
